### ISSUE TITLE
one endpoint giving me error 

### ISSUE THREAD

**Issue by Ampta** [dailycodework/dream-shops#3]
bold part is not working in my system

errors are: 
	at com.ampta.central_shops.service.cart.CartService.initializeNewCart(CartService.java:53) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355) ~[spring-aop-6.1.13.jar:6.1.13]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716) ~[spring-aop-6.1.13.jar:6.1.13]
	at com.ampta.central_shops.service.cart.CartService$$SpringCGLIB$$0.initializeNewCart(<generated>) ~[classes/:na]
	at com.ampta.central_shops.controller.CartItemController.addItemToCart(CartItemController.java:32) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]

@PostMapping("/item/add")
    public ResponseEntity<ApiResponse> addItemToCart(@RequestParam(required = false) Long cartId,
                                                     @RequestParam Long productId,
                                                     @RequestParam Integer quantity){
        try {

            **if (cartId == null) {
                cartId = cartService.initializeNewCart();
            }**

            cartItemService.addItemToCart(cartId, productId, quantity);
            return ResponseEntity.ok(new ApiResponse("Add Item Success", null));
        }catch (ResourceNotFoundException e){
            return ResponseEntity.status(NOT_FOUND).body(new ApiResponse(e.getMessage(), null));
        }

    }

**Comment by YunussEmree** [comment]
Hey, in this code there is no auto initialize cart for default users so you can set the userid manually or integrate spring security. It will be solution for your problem.
